# -*- coding: utf-8 -*-
"""Finding the car price using linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HDiVQj3K_1g2qQCfWZMwkILYRy_4I7wz
"""

from google.colab import files
uploaded = files.upload()

#importing libraries
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

#loading data
train_data = pd.read_csv('train-data.csv')
test_data = pd.read_csv('test-data.csv')

train_data.head()

#dropping unnecessary columns and removing the null and na values
train_data.drop(['Unnamed: 0'],axis=1,inplace=True)
test_data.drop(['Unnamed: 0'],axis=1,inplace=True)

train_data.drop(['New_Price'],axis=1,inplace=True)
test_data.drop(['New_Price'],axis=1,inplace=True)

train_data.drop(['Power'],axis=1,inplace=True)
test_data.drop(['Power'],axis=1,inplace=True)

train_data.dropna(axis=0,how='any',inplace=True)
test_data.dropna(axis=0,how='any',inplace=True)

train_data

#removing the white spaces in the names and removing the units in the columns and converting them into floats
train_data['Name'] = train_data['Name'].str.split(' ', expand = True)
train_data['Name'] = train_data['Name'].replace('ISUZU', 'Isuzu') 

train_data['Mileage'] = train_data['Mileage'].str.split(' ', expand = True)
train_data['Mileage'] = train_data['Mileage'].astype(float)

train_data['Engine'] = train_data['Engine'].str.split(' ', expand = True)
train_data['Engine'] = train_data['Engine'].astype(float)

test_data['Name'] = test_data['Name'].str.split(' ', expand = True)
test_data['Name'] = test_data['Name'].replace('ISUZU', 'Isuzu') 

test_data['Mileage'] = test_data['Mileage'].str.split(' ', expand = True)
test_data['Mileage'] = test_data['Mileage'].astype(float)

test_data['Engine'] = test_data['Engine'].str.split(' ', expand = True)
test_data['Engine'] = test_data['Engine'].astype(float)

train_data

test_data

#grouping unqiue values of the categprical variables

name = list(train_data['Name'].unique())
location = list(train_data['Location'].unique())
fuel_type = list(train_data['Fuel_Type'].unique())
transmission = list(train_data['Transmission'].unique())
owner_type = list(train_data['Owner_Type'].unique())

#getting the dummy variables
train_data = pd.get_dummies(train_data, columns = ['Location', 'Fuel_Type', 'Transmission', 'Owner_Type'], drop_first = True)

train_data

price = train_data.Price
train_data.drop(['Price', 'Name'], axis = 1, inplace = True)
train_data = pd.concat([train_data, price], axis = 1)

train_data

test_data = pd.get_dummies(test_data, columns = ['Location', 'Fuel_Type', 'Transmission', 'Owner_Type'], drop_first = True)
test_data.drop('Name', axis = 1, inplace = True)
test_data

len(train_data.columns)

#intializing the variables x and y
x = train_data.iloc[:, :-1]
y = train_data.iloc[:, 22]

#building the model
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(x, y)

#finding the predictions on the test data set
predictions = lm.predict(test_data)

predictions = pd.Series(predictions)

predictions.head()

#sampling any random 20 values
test = test_data.sample(n = 20)

#finding the predictions of the 20 random values
prediction_test = lm.predict(test)
prediction_test

