# -*- coding: utf-8 -*-
"""Multiple_Linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNBEOJO5vbZ8x7ZoYwyNQZitO28njgxs
"""

from google.colab import files
uploaded = files.upload()

#importing libraries
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

#import data
data = pd.read_csv('50_Startups.csv')

data = pd.get_dummies(data, columns = ['State'], drop_first = True)

profit = data.Profit
data.drop('Profit', axis = 1, inplace =True)

data = pd.concat([data, profit], axis = 1)

X = data.iloc[:, :-1]
Y = data.iloc[:, 5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train, y_train)
predictions = lm.predict(X_test)

#backward elimination
import statsmodels.api as sm
X = np.append(arr = np.ones((50,1)).astype(int),values = X, axis = 1)

X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(Y, X_opt).fit()

regressor_OLS.summary()

X_opt = X[:, [0, 1, 3, 4, 5]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(Y, X_opt).fit()

regressor_OLS.summary()

X_opt = X[:, [0, 3, 4, 5]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(Y, X_opt).fit()

regressor_OLS.summary()

X_opt = X[:, [0, 3, 5]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(Y, X_opt).fit()

regressor_OLS.summary()

X_opt = X[:, [0, 3]]
X_opt = X_opt.astype(np.float64)
regressor_OLS = sm.OLS(Y, X_opt).fit()

regressor_OLS.summary()

